/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Config {
  /**
   * RapidRecovery Web URI
   */
  controllerUri: string;
  zoneConfigFilePath?: string;
  /**
   * Rapid Recovery Authenication Information
   */
  auth: {
    username: string;
    password: string;
  };
  /**
   * Force clearing of existing Schedule, required if changing the crontab string
   */
  overwriteSchedule?: boolean;
  scheduleStartTime?: string;
  /**
   * Default days before a machine triggers an alert due to missed snapshots/backups
   * @default 1
   */
  defaultDaysWithoutBackup?: number;
  /**
   * Optional Teams Channel webhook for ChatOps notifications
   */
  teamsWebHook?: string;
  /**
   * Crontab string for check schedule
   * @default `* /5 * * * *`
   */
  schedule?: string;
  /**
   * Array of RapidRecovery Machines to check and ensure backups/snapshots
   */
  watchedMachines: {
    /**
     * Friendly name of machine to use in logs and notifications
     */
    name: string;
    /**
     * RapidRecovery Machine ID
     */
    id: string;
    /**
     * Days to go since last backup/snapshot before raising any alarms
     */
    daysWithoutBackup?: number;
  }[];
}
