name: Testing

on: [push, pull_request]

jobs:
  Test:
    name: Tests
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        node: ['13.9', '13.10', '13.11', '14.x']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.3
      - uses: actions/setup-node@v2.1.3
        with:
          node-version: ${{ matrix.node }}
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: npm ci
      - name: Run Tests
        run: npm run test

  Build:
    runs-on: ubuntu-latest
    needs: [Test]
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: KristianFJones/Publish-Docker-Github-Action@master
        with:
          dockerfile: Dockerfile
          name: kristianfjones/ts-lazychecker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
